language: ruby
rvm:
  - 2.5.0
  - 2.4.2
  - 2.3.4
  - 2.2.6
gemfile:
  - gemfiles/4.2.gemfile
  - gemfiles/5.0.gemfile
  - gemfiles/5.1.gemfile

addons:
  postgresql: "9.2"

before_script:
  - cp spec/database.yml.travis spec/database.yml
  - bundle exec rake db:setup
