language: ruby
rvm:
  - 2.3.1
  - 2.2.5
gemfile:
  - gemfiles/4.1.gemfile
  - gemfiles/4.2.gemfile
  - gemfiles/5.0.gemfile

addons:
  postgresql: "9.2"

before_script:
  - cp spec/database.yml.travis spec/database.yml
  - bundle exec rake db:setup
