language: ruby
rvm:
  - 2.5.3
  - 2.4.5
  - 2.3.8
gemfile:
  - gemfiles/5.0.gemfile

addons:
  postgresql: "9.2"

before_script:
  - cp spec/database.yml.travis spec/database.yml
  - bundle exec rake db:setup
